# Basic page info
author: hex
description: >-
  Insert Description Here!!

domain: hexaflexahexagon.github.io
baseurl: / # the subpath of your site, e.g. /blog
url: https://hexaflexahexagon.github.io 

# Socials
twitter_username: flexahexagon
github_username: hexaflexahexagon
youtube_username: hex
