# Basic page info
title: MyCoolPage
author: hex
description: >-
  Insert Description Here!!

domain: hexaflexahexagon.github.io
baseurl: / # the subpath of your site, e.g. /blog
url: https://hexaflexahexagon.github.io 
permalink: /post/:title

# Socials
twitter_username: flexahexagon
github_username: hexaflexahexagon
youtube_username: hex
